--import Game.Levels.LogicTruthValue.L01_And
--World "LogicTruthValue"
--Title "Logic Truth Value"
--Introduction "This world will heavily rely on the truth table perspective of propositions and the various logical connective to provide an intuitive foundation for explaining the validity of various rules in propositional logic."
